{ pkgs, lib, ... }:
let
  fishPlugins = [
    {
      name = "hydro";
      src = pkgs.fishPlugins.hydro.src;
    }
  ];

  pluginPaths = lib.concatMapStringsSep "\n" (plugin: ''
    set -gp fish_function_path ${plugin.src}/functions
    set -gp fish_complete_path ${plugin.src}/completions
  '') (lib.filter (p: builtins.pathExists "${p.src}/functions") fishPlugins);

  confDFiles = lib.concatMapStringsSep "\n" (plugin: ''
    if test -d ${plugin.src}/conf.d
      for file in ${plugin.src}/conf.d/*.fish
        source $file
      end
    end
  '') fishPlugins;
in
{
  home.file = lib.listToAttrs (
    map (plugin: {
      name = ".local/share/fish/nix-plugins/${plugin.name}";
      value = {
        source = plugin.src;
        recursive = true;
      };
    }) fishPlugins
  );

  xdg.configFile."fish/conf.d/00-nix-plugins.fish".text = ''
    # Nix-managed Fish plugins
    # This file is automatically generated by Home Manager

    ${pluginPaths}

    # Source conf.d files from plugins
    ${confDFiles}
  '';

  xdg.configFile."fish/conf.d/01-nix-darwin-path.fish".text = ''
    # Add nix-darwin system packages to PATH
    if test -d /run/current-system/sw/bin
      fish_add_path /run/current-system/sw/bin
    end
  '';
}
