fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

if command -v fzf >/dev/null 2>&1; then
  eval "$(fzf --zsh)"
fi
